### ISSUE TITLE
 java.lang.NoClassDefFoundError when switching to Nuix Engine engine-dist-win32-amd64-9.6.6.317

### ISSUE THREAD

**Issue by chrishaupt** [Nuix/Nuix-Java-Engine-Baseline#13]
I am developing a project based on Nuix-Java-Engine-Baseline and the Nuix Engine. When switching the engine from 9.2.4.392 to 9.6.6.317 the execution of my program runs into an error. When using it with the engine version 9.2.4.392 it runs just fine.

```
C:\Users\user\Desktop\casemaker-0.0.1-SNAPSHOT>"C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot\bin\java.exe" -Xms2G -Xmx2G -Dlog4j.configurationFile="C:\Users\user\Desktop\casemaker-0.0.1-SNAPSHOT\log4j2-nuix-9.yml" -Dnuix.logdir="C:\Nuix\engine-dist-win32-amd64-9.6.6.317\logs\20220102174752" -Dnuix.libdir="C:\Nuix\engine-dist-win32-amd64-9.6.6.317\lib" -cp lib\*;C:\Nuix\engine-dist-win32-amd64-9.6.6.317\lib\* de.comp.nuix.api.CreateCase "C:\Nuix\CaseFolder" "TestCase" "C:\Nuix_Evidence\Language_Test"
2022-02-01 17:47:53.833 +0100 [main] 1684 INFO  de.comp.nuix.common.config.DataBridgeConfigurator - DataBridgeConfig gefunden in: dataBridgeConfig.json
2022-02-01 17:47:53.848 +0100 [main] 1699 INFO  de.comp.nuix.api.EngineWrapper - Setting 'nuix.libdir' to: C:\Nuix\engine-dist-win32-amd64-9.6.6.317\lib
2022-02-01 17:47:53.864 +0100 [main] 1715 INFO  de.comp.nuix.api.EngineWrapper - Creating GlobalContainer...
2022-02-01 17:47:54.834 +0100 [main] 2685 INFO  com.nuix.storage.lowlevel.graph.a - Setting un-specified OrientDB System property 'memory.leftToOS' to Nuix default of '90%'.
2022-02-01 17:47:54.834 +0100 [main] 2685 INFO  com.nuix.storage.lowlevel.graph.a - Setting un-specified OrientDB System property 'memory.useUnsafe' to Nuix default of 'false'.
2022-02-01 17:47:54.834 +0100 [main] 2685 INFO  com.nuix.storage.lowlevel.graph.a - Setting un-specified OrientDB System property 'storage.compressionMethod' to Nuix default of 'gzip'.
2022-02-01 17:47:55.447 +0100 [main] 3298 INFO  com.nuix.util.concurrent.d - Initialising with 2 IO threads
2022-02-01 17:47:55.460 +0100 [main] 3311 INFO  com.nuix.util.concurrent.d - Initialising with 4 store threads
2022-02-01 17:47:55.622 +0100 [main] 3473 INFO  com.nuix.util.jvm.classloader.EngineBootstrapClassLoader - EngineBootstrapClassLoader invoked.
2022-02-01 17:47:55.660 +0100 [main] 3511 INFO  com.nuix.util.jvm.classloader.EngineBootstrapClassLoader - Trying to load JARS under this path- C:\Nuix\engine-dist-win32-amd64-9.6.6.317\lib\non-fips
2022-02-01 17:47:55.660 +0100 [main] 3511 INFO  com.nuix.util.jvm.classloader.EngineBootstrapClassLoader - Valid ClassLoader Module Path resolved to C:\Nuix\engine-dist-win32-amd64-9.6.6.317\lib\non-fips
2022-02-01 17:47:55.776 +0100 [main] 3627 WARN  com.nuix.util.jvm.classloader.EngineBootstrapClassLoader - Failed to invoke Load Module for EngineBootStrapClassLoader as java.base does not export jdk.internal.loader to unnamed module
2022-02-01 17:47:55.776 +0100 [main] 3627 INFO  com.nuix.util.crypto.i - NuixSecurityServices created in non-FIPS mode
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.nuix.storage.lowlevel.graph.internal.impl.orientdb.e (file:/C:/Nuix/engine-dist-win32-amd64-9.6.6.317/lib/nuix-storage-lowlevel-9.6.6.317.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.nuix.storage.lowlevel.graph.internal.impl.orientdb.e
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-02-01 17:47:55.776 +0100 [main] 3627 INFO  de.comp.nuix.api.EngineWrapper - Removing shutdown hook to EngineWrapper::close
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
        at com.nuix.util.crypto.i.a(SourceFile:35)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at com.nuix.util.k.e(SourceFile:107)
        at com.nuix.util.jvm.classloader.EngineBootstrapClassLoader.b(SourceFile:86)
        at com.nuix.util.jvm.classloader.EngineBootstrapClassLoader.run(SourceFile:81)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at com.nuix.engine.e.<init>(SourceFile:49)
        at com.nuix.engine.DefaultGlobalContainerFactory.createSpi(SourceFile:23)
        at nuix.engine.GlobalContainerFactory.newContainer(SourceFile:60)
        at de.comp.nuix.api.EngineWrapper.withServerLicense(EngineWrapper.java:189)
        at de.comp.nuix.api.CreateCase.main(CreateCase.java:95)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 11 more

C:\Users\user\Desktop\casemaker-0.0.1-SNAPSHOT>PAUSE
```

I would expect it to run in the new version as in the old version.

**Comment by JuicyDragon** [comment]
Hello @chrishaupt this recently came up elsewhere and I have only recently learned of the solution, so I haven't yet had a chance to push up changes to reflect that solution.

This has to do with 9.6 using Java 11 and resolving particular crypto dependencies at run-time.  Basically the JVM now needs to be passed this argument:

`--add-exports=java.base/jdk.internal.loader=ALL-UNNAMED`

I'll see if I can get this worked into the project here, until I do, I believe including that argument should resolve this issue.

**Comment by chrishaupt** [comment]
Hi @JuicyDragon, this solves the problem! Thanks.

Another way I found yesterday was to add the bouncycastle dependencies (from the engine lib/non-fips directory) to the pom of my project. But I will stick to your way as it is more consise.

**Comment by JuicyDragon** [comment]
At run-time Nuix decides to go the FIPS or NON-FIPS route and dynamically loads some dependencies from the appropriate sub-directory.  That dynamic dependency resolution seems to be the reason that argument is needed.  While you might take another approach as you mentioned, I'm not sure if that has potential downsides.  A senior member of the engine team told me that argument was the necessary magic to get this working so I'd say that's a good way to go 😄 

Glad that worked for you.  I'm exploring converting this project into a Gradle project due to some experience I've had to Gradle recently.  Once I get there, the argument would be part of the build file and would be more of an after thought.
